version: '3'
services:
  neo4j:
    container_name: neo4j
    image: neo4j:4.4.16-community
    ports:
      - 7474:7474
      - 7687:7687
    volumes: 
      - ./neo4j/conf:/conf
      - ./neo4j/logs:/logs
      # - ./neo4j/data:/data
      - ./neo4j/ssl/bolt:/var/lib/neo4j/certificates/bolt
      - ./neo4j/ssl/https:/var/lib/neo4j/certificates/https
    environment:
      - NEO4J_AUTH=neo4j/password
